### ISSUE TITLE
Stat roll only as disadvantage available for rolling

### ISSUE THREAD

**Issue by jwylie01** [fvtt-fria-ligan/blade-runner-foundry-vtt#7]
### Describe the bug

When clicking an attribute to make a roll, strength for instance, when the roll form opens, the only button available for clicking is "Disadvantage". The roll doesn't actually change the base die rolled though.

Should all 3 options be available if the player needs to apply an advantage or disadvantage to the roll? 

### Reproduction

Click on one of the 4 main attributes on the player sheet. Only button that is active to make a roll is "disadvantage"

### System Info

```sh
Foundry V10 Build 290
The Forge for hosting
Blade Runner 10.0.1
Blade Runner RPG Start Set Version 1.0.1
Blade Runner RPG Core Rules Version 1.0.1

```

### Priority this issue should have?

Medium (minor functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Blade Runner system).

**Comment by Stefouch** [comment]
Because there is only one die (the attribute), the program considers that you are going to roll as disadvantaged, enabling only the disadvantage button.

Since you cannot roll less than 1 die, clicking the disadvantage button will change nothing of course.

Now, if you want to roll that sole die with advantage, you can manually add an extra die: click the "+" button near the dice in the roll dialog. You now have 2 dice and all 3 buttons are enabled.
